[package]
authors = ["Chris Swindle <christopher.swindle@metaswitch.com>"]
name = "hyper-dns"
version = "0.1.0"

[dependencies]
futures = "0.1.14"
hyper = "0.10.12"
rand = "0.3.15"
tokio-core = "0.1.8"
trust-dns = "0.9.3"
