[package]
authors = ["Chris Swindle <christopher.swindle@metaswitch.com>"]
name = "hyper-dns"
description = "This crates provides a NetworkConnector for Hyper which adds the ability to perform SRV lookups on URLs."
version = "0.1.3"
license = "MIT"
repository = "https://github.com/cswindle/hyper-dns"
keywords = ["hyper", "dns"]

[badges]
travis-ci = { repository = "cswindle/hyper-dns" }

[dependencies]
futures = "0.1.14"
hyper = "0.10.12"
rand = "0.3.15"
tokio-core = "0.1.8"
trust-dns = "0.9.3"
